{% set name = "stellarmesh" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e53c8b4b4455e7e996a7b0f6dd8d1a54f81932f3a8f29ed9278ccaa39e0a3b1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [win or py<311]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - python-gmsh
    - ocp >=7.7.2.1
    - moab
    - numpy
    - mmgsuite
    - meshio
    - libgl  # [linux]

test:
  imports:
    - stellarmesh

about:
  home: https://github.com/stellarmesh/stellarmesh
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Meshing library for nuclear workflows"
  description: |
    Stellarmesh is a meshing library for nuclear workflows. Principally, it
    supports the creation of DAGMC geometry from CAD models using the gmsh
    library. Stellarmesh supports both build123d and CadQuery for geometry
    construction but does not depend on either.
  dev_url: https://github.com/stellarmesh/stellarmesh

extra:
  recipe-maintainers:
    - paulromano
    - akoen
