{% set name = "stellarmesh" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6dd1aa95fb4e0d2c8fa6dadb1a1529230d2d7c80e49ab19981e315b4543be9ad

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [win or py<310]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - python-gmsh
    - numpy
    - moab
    - ocp
    - mmgsuite
    - libgl  # [linux]

test:
  imports:
    - stellarmesh

about:
  home: https://github.com/stellarmesh/stellarmesh
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Meshing library for nuclear workflows"
  description: |
    Stellarmesh is a meshing library for nuclear workflows. Principally, it
    supports the creation of DAGMC geometry from CAD models using the gmsh
    library. Stellarmesh supports both build123d and CadQuery for geometry
    construction but does not depend on either.
  dev_url: https://github.com/stellarmesh/stellarmesh

extra:
  recipe-maintainers:
    - paulromano
