{% set name = "stellarmesh" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ae62b8ab4c0a6bf578fc56d59498404e4cdcfd805b8dbb18aefbb619b32b044b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [win or py<311]

requirements:
  host:
    - python
    - pip
    - setuptools >=80
    - setuptools-scm >=8
  run:
    - python
    - python-gmsh >=4
    - ocp >=7.7.2.1
    - moab
    - numpy
    - mmgsuite
    - meshio
    - libgl  # [linux]

test:
  imports:
    - stellarmesh

about:
  home: https://github.com/stellarmesh/stellarmesh
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Meshing library for nuclear workflows"
  description: |
    Stellarmesh is a meshing library for nuclear workflows. Principally, it
    supports the creation of DAGMC geometry from CAD models.
    doc_url: https://stellarmesh.readthedocs.io/
  dev_url: https://github.com/stellarmesh/stellarmesh

extra:
  recipe-maintainers:
    - paulromano
    - akoen
